version: "3"
services:

  db:
    image: "postgres:15-alpine3.18"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=web_proekt_baza
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  backend:
    image: "matejdjajkov/backend"
    container_name: "backend"
    environment:
      - POSTGRES_HOST=db
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: "matejdjajkov/frontend"
    container_name: "frontend"
    ports:
      - "3000:3000"
    depends_on:
      - backend