apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev 
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: matejdjajkov/backend
          name: backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: simple-configmap
                key: POSTGRES_HOST